name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: stable

      - uses: JohnnyMorganz/stylua-action@v4
        with:
          version: latest
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check formatting
        run: stylua --check lua

      - name: Run tests
        run: nvim --headless -u NONE -c 'set rtp+=.' -c 'luafile lua/neotest-dart/tests/run.lua' -c 'qa'
